[project]
name = "decompile-contract"
version = "0.0.1"

dependencies = [
    "requests ~= 2.32.3",
    "joblib ~= 1.4.2",
]

[build-system]
requires = ["setuptools >= 70.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src/"]